# Generated by Django 5.2.17 on 2026-09-28 06:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.content.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="区域名称")),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True, verbose_name="分类名称")),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="HandbookSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="章节标题")),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(20000)],
                        verbose_name="章节正文",
                    ),
                ),
                ("published", models.BooleanField(default=False, verbose_name="已发布")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                ("summary", models.CharField(max_length=500, verbose_name="摘要")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("latest", "最新活动"),
                            ("news", "资讯信息"),
                            ("past", "往期回顾"),
                        ],
                        max_length=12,
                        verbose_name="分类",
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True, verbose_name="活动时间")),
                ("location", models.CharField(blank=True, max_length=250, verbose_name="地点")),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(20000)],
                        verbose_name="正文",
                    ),
                ),
                (
                    "article_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[apps.content.validators.validate_article_url],
                        verbose_name="公众号原文",
                    ),
                ),
                ("published", models.BooleanField(default=False, verbose_name="已发布")),
                ("is_example", models.BooleanField(default=False, verbose_name="示例内容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("category__in", ["latest", "news", "past"])),
                        name="content_activity_category_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                (
                    "image_url",
                    models.URLField(
                        max_length=1000,
                        validators=[apps.content.validators.validate_https_url],
                        verbose_name="图片网址",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[("none", "不跳转"), ("merchant", "商家"), ("post", "论坛帖子")],
                        default="none",
                        max_length=12,
                        verbose_name="跳转类型",
                    ),
                ),
                (
                    "link_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="目标编号",
                    ),
                ),
                ("published", models.BooleanField(default=False, verbose_name="已发布")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "ordering": ["sort_order", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("link_type__in", ["none", "merchant", "post"])),
                        name="content_banner_link_type_valid",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[apps.content.validators.validate_https_url],
                        verbose_name="官方网站",
                    ),
                ),
                (
                    "assistant_wechat",
                    models.CharField(blank=True, max_length=100, verbose_name="小助手微信号"),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="content_support_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("suggestion", "功能建议"),
                            ("bug", "使用问题"),
                            ("merchant", "商家信息"),
                        ],
                        max_length=12,
                        verbose_name="反馈类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(1000),
                        ],
                        verbose_name="反馈内容",
                    ),
                ),
                ("contact", models.CharField(blank=True, max_length=100, verbose_name="联系方式")),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "待处理"), ("resolved", "已处理")],
                        default="new",
                        max_length=12,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                        verbose_name="处理备注",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("category__in", ["suggestion", "bug", "merchant"])),
                        name="content_feedback_category_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["new", "resolved"])),
                        name="content_feedback_status_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="商家名称")),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        validators=[apps.content.validators.validate_https_url],
                        verbose_name="Logo 网址",
                    ),
                ),
                ("discount_summary", models.CharField(max_length=300, verbose_name="优惠摘要")),
                (
                    "intro",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(10000)],
                        verbose_name="商家介绍",
                    ),
                ),
                (
                    "discount_terms",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(5000)],
                        verbose_name="优惠使用条件",
                    ),
                ),
                (
                    "image_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.content.validators.validate_image_urls],
                        verbose_name="图片网址列表",
                    ),
                ),
                ("address", models.CharField(max_length=500, verbose_name="地址")),
                (
                    "latitude",
                    models.FloatField(
                        validators=[apps.content.validators.validate_latitude], verbose_name="纬度"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[apps.content.validators.validate_longitude], verbose_name="经度"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="联系电话")),
                (
                    "opening_hours",
                    models.CharField(blank=True, max_length=500, verbose_name="营业时间"),
                ),
                ("published", models.BooleanField(default=False, verbose_name="已上架")),
                ("featured", models.BooleanField(default=False, verbose_name="首页精选")),
                ("is_example", models.BooleanField(default=False, verbose_name="示例商家")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merchants",
                        to="content.area",
                        verbose_name="区域",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merchants",
                        to="content.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                        name="content_merchant_latitude_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                        name="content_merchant_longitude_valid",
                    ),
                ],
            },
        ),
    ]
